### ISSUE TITLE
Missing launch_ui

### ISSUE THREAD

**Issue by samraul** [qiminchen/ShaDDR#1]
Hi Qimin,

Thanks for sharing the code, weights and data.
Do you plan on releasing the code for the UI mentioned in the paper?

Thank you.

**Comment by qiminchen** [comment]
Sorry I was not aware that the GUI is missing, will update the code around mid Dec since I have a few deadlines to catch up

**Comment by samraul** [comment]
Great, thanks!

I was able to easily port decor-gan's UI to shaddr (only geometry, not textured), and it is already very helpful to explore the latent space. Being able to modify the coarse input easily as well is a nice addition.

**Comment by qiminchen** [comment]
Hi @samraul , I've updated the code and instruction for GUI, please let me know if you have questions.

**Comment by samraul** [comment]
Awesome. Thanks for the update.
