### ISSUE TITLE
preprocessing - start Generator number of parameters: 35,581,605 Start testing texture...  [!] Load failed...

### ISSUE THREAD

**Issue by kuaiqushangzixiba** [qiminchen/ShaDDR#2]
preprocessing - start
Generator number of parameters: 35,581,605
Start testing texture...
 [!] Load failed...

what should i do。。。。

![image](https://github.com/qiminchen/ShaDDR/assets/42159103/e6b56c52-b2c8-4757-84ac-1eede5158605)
![image](https://github.com/qiminchen/ShaDDR/assets/42159103/c90feae3-54cb-4445-8bcd-a368d0f47a0e)
![image](https://github.com/qiminchen/ShaDDR/assets/42159103/0db60be0-fa71-46cb-a72c-ce2c1cd08408)
![image](https://github.com/qiminchen/ShaDDR/assets/42159103/23443098-0f30-4056-a12a-7ecb76fabe13)

thanks very much！

**Comment by triplewhopper** [comment]
Hello,
for example in 02958343/checkpoint:
change 
`checkpoint/style_color_plane_16_aemr_texture/IM_AE.model.pth` 
to
`checkpoint/02958343/style_color_plane_16_aemr_texture/IM_AE.model.pth`
and line 816 of `modelAEH.py`:
from
`return "{}_aemr".format(self.data_style)`
to
`return "{}_aemr_texture".format(self.data_style)`

I'm not sure if it is correct, but apparently it works.

**Comment by qiminchen** [comment]
Hi @kuaiqushangzixiba, sorry for the confusion, and yes @triplewhopper solution is correct, I will clean the code asap

**Comment by kuaiqushangzixiba** [comment]
![image](https://github.com/qiminchen/ShaDDR/assets/42159103/a5959586-9df6-4e97-9ef0-a484a9cc3c80)
![image](https://github.com/qiminchen/ShaDDR/assets/42159103/1207c99d-5ff7-4810-b11f-c453dc698e50)


oh, thank you very much for your help, I successfully tested the method on car! However, on the construction, I still did not succeed, error screenshot below.
The following information is displayed when using input 32
![image](https://github.com/qiminchen/ShaDDR/assets/42159103/6d7b3977-c691-49bd-9ce3-21366d097bd1)

The following information is displayed when input 64 is used

![image](https://github.com/qiminchen/ShaDDR/assets/42159103/7bd4de64-6741-42f4-9cd4-7c2d471f2693)


what should i do....

**Comment by kuaiqushangzixiba** [comment]
oh ，sorry， use follow settings successfully，good job！！！

# note -- valid settings:
# input 64, output 256, x4
# input 32, output 128, x4
# input 32, output 256, x8
# input 16, output 128, x8
