### ISSUE TITLE
data preparation  I wanted to try this on my own dataset

### ISSUE THREAD

**Issue by kuaiqushangzixiba** [qiminchen/ShaDDR#3]
I wanted to try this on my own dataset，only obj without mtl and no-color，like this...
![image](https://github.com/qiminchen/ShaDDR/assets/42159103/72eeb75a-44af-4f00-96e8-dd911dc926bf)

I found this note

NOTE: We use the exact same content shapes as [DECOR-GAN](https://github.com/czq142857/DECOR-GAN/tree/main#datasets-and-pre-trained-weights) (Ready-to-use data is available). If you need to use your own content shapes, please refer to [DECOR-GAN](https://github.com/czq142857/DECOR-GAN/blob/main/data_preparation/README.md) for the original data preprocessing code for preparing content shapes. Here, we provide code for preparing colored-style shapes.

I have an obj with no texture. What data preparation code should I use to process the data? Data preparation method in DECOR-GAN, or shaddr. Or does it must have to be colored-style shapes. Thank you very much!

**Comment by qiminchen** [comment]
Hi, if you only want to perform **geometry** detailization, you could use the data preparation code in DECOR-GAN.

You need colored style shapes if you want to perform texture detailization

**Comment by kuaiqushangzixiba** [comment]
Oh，thankyou，I notice that the generated points have color on them, so can I give my uncolored mesh vertices a random color and then use ShaDDR to operate on it?

**Comment by qiminchen** [comment]
yes, but if colors/material are defined on the mesh vertices instead of `.mtl` file, you might need to modify the `render.py` by adding codes below
```
# add a new material
mat = bpy.data.materials.new(name="MATERIAL")
# add material to object that is to be rendered
bpy.data.objects[file_name].data.materials.append(mat)
mat.use_nodes = True
# add a vertex color node, "Vertex Color" might need to change to "Color Attribute" for higher version of blender
# "Col" is the color name, should be changed accordingly if needed
mat.node_tree.nodes.new(type="ShaderNodeVertexColor")
mat.node_tree.nodes["Vertex Color"].layer_name = "Col"
mat.node_tree.nodes["Principled BSDF"].inputs['Specular'].default_value = 0
mat.node_tree.nodes["Principled BSDF"].inputs['Roughness'].default_value = 1
# "Principled BSDF" is shader type, change to other for other shaders if want
bsdf = mat.node_tree.nodes["Principled BSDF"].inputs["Base Color"]
output = mat.node_tree.nodes["Vertex Color"].outputs["Color"]
# link vertex color node to shader
mat.node_tree.links.new(output, bsdf)
```

**Comment by kuaiqushangzixiba** [comment]
Ok! Now I only have a mesh without color, what do you think is the most convenient way for me to deal with it? Is there any script to specify mtl for a mesh without color... Thank you !

**Comment by qiminchen** [comment]
you will need to model texture by yourself using some 3d modeling software such as blender

**Comment by kuaiqushangzixiba** [comment]
Ok, one more blender question, is there a different version of blender, I want to know what version of blender you have

`(shaddr) root@2ec73dfa4a5a:/data/ShaDDR/data_preparation# ./blender/blender-4.1.1-linux-x64/blender -b render_views.blend  --python render.py
Blender 4.1.1 (hash e1743a0317bc built 2024-04-15 23:47:45)
Warning: Falling back to the standard locale ("C")
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
Read blend: "/data/ShaDDR/data_preparation/render_views.blend"
Warning: region type 11 missing in space type "Info" (id: 7) - removing region
usage: blender [-h] class_id share_id share_total
blender: error: argument share_id: invalid int value: 'render.py'
(shaddr) root@2ec73dfa4a5a:/data/ShaDDR/data_preparation# `


blender: error: argument share_id: invalid int value: 'render.py'

**Comment by qiminchen** [comment]
we use blender 2.93, and please try this command line
```
./blender/blender render_views.blend --background --python render.py <class_id> <process_id> <total_num_of_processes>
e.g.
./blender/blender render_views.blend --background --python render.py 03001627 0 1
```
alternatively, you could remove lines 4-8 and hard code lines 10-12 and run `./blender/blender render_views.blend --background --python render.py`
https://github.com/qiminchen/ShaDDR/blob/5914f197e88c9088aa67d4b6eb9cdd443a73e0ad/data_preparation/render.py#L4-L12

**Comment by kuaiqushangzixiba** [comment]
![image](https://github.com/qiminchen/ShaDDR/assets/42159103/ed14510d-d831-4c99-abc6-841f5798483c)


ohyes， remove lines 4-8 and hard code lines 10-12 ，use blender2.93，6 views were successfully generated

but
use“ ./blender/blender render_views.blend --background --python render.py 03001627 0 1  “，failed
But no matter how I modify the pass-parameter logic, it doesn't seem to be right, it doesn't seem to pass the parameter correctly, right
![image](https://github.com/qiminchen/ShaDDR/assets/42159103/16b83669-1406-4517-a483-50559250d901)


Anyway, I will use hard code to operate first, thank you!

**Comment by kuaiqushangzixiba** [comment]
![image](https://github.com/qiminchen/ShaDDR/assets/42159103/d92ecd71-1cbc-489b-8b7b-8e1de98c870f)

Problems encountered when compiling cython
This caused me to get python 4_get_colored_voxels.py 03001627 0 4 wrong

  File "4_get_colored_voxels.py", line 9, in <module>
    import get_point_cloud
ModuleNotFoundError: No module named 'get_point_cloud'



I notice that only the cutils.pyx file is provided, not the getpointcloud.pyx file

**Comment by kuaiqushangzixiba** [comment]
The other question is, if we only use inference, just the first three steps of data preparation, generating depthfusion.binvox seems to be enough for inference, right?

**Comment by qiminchen** [comment]
Sorry for the missing file, I just uploaded the `get_point_cloud.py` under the data_preparation folder, please rebuild the Cython module and try again.

And yes, if you only want to do inference, the first three step is enough

**Comment by kuaiqushangzixiba** [comment]
Can add texture without changing the shape of the mesh or just small details? Because my mesh shape is weird, it changes a little bit after using it...Thank you !

The following screenshot shows the mesh on the left and the mesh with the changed shape after generation on the right
![image](https://github.com/qiminchen/ShaDDR/assets/42159103/e739c356-3a70-4ae2-8a1f-17964e253df4)

**Comment by qiminchen** [comment]
The building output looks like the symmetry was used, we trained our building category without symmetry assumption, can you add `--asymmetry` when running the testing command?

**Comment by kuaiqushangzixiba** [comment]
![image](https://github.com/qiminchen/ShaDDR/assets/42159103/47543dfa-1a53-48ef-af24-0b0d1179ea3b)
ok, you are right, it is much better after I add the asymmetric parameter, but I still want to ask if there is a way to make it closer to the original shape, thank you very much!

some shapes are very close, but I noticed that it seems like a lot of the results have some rotation angles.


I noticed that my input mesh doesn't have an Angle along the xy axis, but the output seems to be along the xy direction, which seems to be the reason for the large shape change

![image](https://github.com/qiminchen/ShaDDR/assets/42159103/29d53196-7b3e-4975-a46e-db17048969c5)

**Comment by kuaiqushangzixiba** [comment]
Or, if my input is a triangle, does it force the output shape to be a square

**Comment by qiminchen** [comment]
We do require the coarse voxel to align with the axis, for car, airplane and chair, the default orientation can be found in DECOR-GAN, for building and plant, since we randomly rotate the coarse voxel along y-axis on a 90-degree basis, we do require the input coase voxel to be axis-aligned.

And we have not tested our model on a triangle-like shape, ShaDDR cannot handle coarse voxel whose global structure if completely out-of-distribution.

**Comment by VLadImirluren** [comment]
> Sorry for the missing file, I just uploaded the `get_point_cloud.py` under the data_preparation folder, please rebuild the Cython module and try again.
> 
> And yes, if you only want to do inference, the first three step is enough

But get_point_cloud.pyx still missing, which is required in setup.py

**Comment by qiminchen** [comment]
> > Sorry for the missing file, I just uploaded the `get_point_cloud.py` under the data_preparation folder, please rebuild the Cython module and try again.
> > And yes, if you only want to do inference, the first three step is enough
> 
> But get_point_cloud.pyx still missing, which is required in setup.py

Hi, sorry for the missing file, I just uploaded the `get_point_cloud.pyx`, please try again
